/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SeleniumTrainingCarlos;



import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

public class formsTests {
	static WebDriver driver = new ChromeDriver();
	
	static formsKeys fk = new formsKeys();
	static formsMethods fm = new formsMethods();

	private static final String expectedMandatoryMessage = "This field is required.";
	private static final String expectedPartyRockMessage = "Let's party rock.";	
	private static final String name="Carlos";	
	private static final String date="08/10/1990";	
	private static final String comment="I like to find bugs";	
	private static final String expectedSuccesfulMessage = "Information sent successfully!";

	@BeforeClass
	public static void setupClass() {
		System.setProperty("webdriver.chrome.driver", "/Users/cbrichete/Desktop/Selenium/seleniumStudy/Software/chromedriver");
	}
	
	@Before
	public void setUpTest() {
		driver.get("https://forms.liferay.com/web/forms/shared/-/form/122548");
	}
	
	@AfterClass
	public static void teardown() {
		driver.close();
	}
	
	@Test
	public void mandatoryNameField() {			
		fm.clickSubmitButton();
		
		String currentValue = driver.findElement(By.xpath(fk.getNameFieldRequiredText())).getText();

		Assert.assertTrue(currentValue.contains(expectedMandatoryMessage));
	}
	
	@Test
	public void mandatoryDateField() {			
		fm.clickSubmitButton();
		
		String currentValue = driver.findElement(By.xpath(fk.getDateFieldRequiredText())).getText();
		
		Assert.assertTrue(currentValue.contains(expectedMandatoryMessage));
	}
	
	@Test
	public void mandatoryCommentField() {			
		fm.clickSubmitButton();
		
		String currentValue = driver.findElement(By.xpath(fk.getCommentFieldRequiredText())).getText();
		
		Assert.assertTrue(currentValue.contains(expectedMandatoryMessage));
	}
		
	@Test
	public void textPresent() {	
		String currentValue = driver.findElement(By.xpath(fk.getPartyRockText())).getText();
		
		Assert.assertTrue(currentValue.contains(expectedPartyRockMessage));
	}

	@Test
	public void successfulSubmit() {
		fm.succesfulMessage(name, date, comment);
			
		String currentValue = driver.findElement(By.xpath(fk.getSuccesfulMessage())).getText();
		
		Assert.assertTrue(currentValue.contains(expectedSuccesfulMessage));
	}
}


